---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: berkelana-web
  namespace: demo-gke
spec:
  selector:
    matchLabels:
      app: berkelana
  replicas: 2
  template:
    metadata:
      labels:
        app: berkelana
    spec:
      containers:
        - name: berkelana
          image: gcr.io/horizontal-ally-383421/berkelana:v53
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: berkelana-service
  namespace: demo-gke
spec:
  type: LoadBalancer
  selector:
    app: berkelana
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
      nodePort: 30748
