---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: berkelana-web
  namespace: gke-test
spec:
  selector:
    matchLabels:
      app: berkelana
  replicas: 2
  template:
    metadata:
      labels:
        app: berkelana
    spec:
      containers:
        - name: berkelana
          image: 151231214213.dkr.ecr.ap-southeast-2.amazonaws.com/berkelana:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: berkelana-service
  namespace: gke-test
spec:
  type: LoadBalancer
  selector:
    app: berkelana
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
